[package]
name = "clew-host"
version.workspace = true
edition.workspace = true

[dependencies]
clew-core = { path = "../clew-core" }
clew-identity = { path = "../clew-identity" }
clew-transport = { path = "../clew-transport" }
getrandom.workspace = true
hostname.workspace = true
iroh.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
